#!/bin/bash

PNAMES="(prod|staging)"
PORTS=("prod:301" "staging:302")
CMDS="(up|down|restart|ps|logs|pull|images|stop|start)"
DIR=/opt/docker/login
export NAME=login

###############################################################################
bin=$(basename "$0")
usage() {
  echo "Usage:"
  echo "  $bin $PNAMES $CMDS OPTS"
  echo
  echo "Examples:"
  echo "  $bin prod up -d --build"
  echo "  $bin prod restart edu"
  echo "  $bin staging down"
  exit "$1"
}

[ "$1" = 'help' -o "$1" = 'usage' ] && usage 0

pname="$1"
echo "$pname"|grep -Eq "^$PNAMES$" || usage 1
shift
cmd="$1"
echo "$cmd"|grep -Eq "^$CMDS$" || usage 1
shift

for p in "${PORTS[@]}"; do [ "${p%%:*}" = "$pname" ] && export PORT="${p##*:}"; done

#docker-compose -f "/opt/docker/$pname/docker-compose.yml" "$cmd" $@
#docker-compose -f "/opt/docker/login/docker-compose-$pname.yml" -p "$pname" "$cmd" $@
#COMPOSE_PROJECT_NAME="$pname" docker-compose -f "/opt/docker/$pname/docker-compose.yml" "$cmd" $@
COMPOSE_PROJECT_NAME="$pname" docker-compose -f "$DIR/docker-compose.yml" -f "$DIR/docker-compose.$pname.yml" "$cmd" $@
