#!/bin/bash

PNAMES="(test|ndoroshenko|d2d4)"
PORTS=("test:303" "d2d4:304" "ndoroshenko:305")
CMDS="(up|down|restart|ps|logs|images|build|stop|start)"
DIR=/opt/docker/login

###############################################################################
bin=$(basename "$0")
usage() {
  echo "Usage:"
  echo "  $bin $PNAMES $CMDS OPTS"
  echo
  echo "Examples:"
  echo "  $bin test up -d --build"
  echo "  $bin test restart edu"
  echo "  $bin ndoroshenko down"
  exit "$1"
}

[ "$1" = 'help' -o "$1" = 'usage' ] && usage 0

pname="$1"
echo "$pname"|grep -Eq "^$PNAMES$" || usage 1
shift
cmd="$1"
echo "$cmd"|grep -Eq "^$CMDS$" || usage 1
shift

for p in "${PORTS[@]}"; do [ "${p%%:*}" = "$pname" ] && export PORT="${p##*:}"; done
[ $pname = 'test' ] && dname='test' || dname='dev'

#docker-compose -f "/opt/docker/$pname/docker-compose.yml" "$cmd" $@
#docker-compose -f "/opt/docker/login/docker-compose-$pname.yml" -p "$pname" "$cmd" $@
#COMPOSE_PROJECT_NAME="$pname" docker-compose -f "/opt/docker/$dname/docker-compose.yml" "$cmd" $@
COMPOSE_PROJECT_NAME="$pname" docker-compose -f "$DIR/docker-compose.yml" -f "$DIR/docker-compose.$dname.yml" "$cmd" $@
